name: toto_profile_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0  # <<< Tambahkan disini!
  provider: ^6.1.1
  loading_animation_widget: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/project/

